/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimise a circuit for an IBM backend (IBM Composer + Classiq redundancy)
         * @description Upload a circuit → transpile/optimise for `target_backend` → simulate → estimate cost →
         *     business interpretation. `redundancy_mode` controls IBM/Classiq fallback or parallel runs.
         */
        post: operations["optimize_v2_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quote QPU time and cost for IBM Composer and Classiq without executing */
        post: operations["quote_v2_quote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Business-language interpretation of measurement results */
        post: operations["interpret_v2_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List this customer's jobs */
        get: operations["list_jobs_v2_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job detail (payloads decrypt only with the original X-Payload-Key) */
        get: operations["get_job_v2_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackendEstimate */
        BackendEstimate: {
            backend: components["schemas"]["OptimizationBackend"];
            /**
             * Status
             * @description estimated | assumed | not_applicable | error
             */
            status: string;
            /** Note */
            note?: string | null;
            /** Depth */
            depth?: number | null;
            /** Gate Count */
            gate_count?: number | null;
            /** Estimated Qpu Runtime Sec */
            estimated_qpu_runtime_sec?: number | null;
            /**
             * Estimated Qpu Cost Usd
             * @description Cost per plan for this backend.
             */
            estimated_qpu_cost_usd?: {
                [key: string]: number;
            } | null;
        };
        /** BackendResult */
        BackendResult: {
            backend: components["schemas"]["OptimizationBackend"];
            /**
             * Status
             * @description success | error | timeout | not_applicable | skipped
             */
            status: string;
            /** Reason */
            reason?: string | null;
            /** Depth */
            depth?: number | null;
            /** Gate Count */
            gate_count?: number | null;
            /** Two Qubit Gate Count */
            two_qubit_gate_count?: number | null;
            /** Width */
            width?: number | null;
            /** Estimated Qpu Runtime Sec */
            estimated_qpu_runtime_sec?: number | null;
            /** Estimated Qpu Cost Usd */
            estimated_qpu_cost_usd?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            transpiled_circuit?: components["schemas"]["TranspiledCircuit"] | null;
            metrics?: components["schemas"]["CircuitMetrics"] | null;
        };
        /** Billing */
        Billing: {
            plan: components["schemas"]["BudgetPlan"];
            /** Qpu Cost Usd */
            qpu_cost_usd: number;
            /** Service Fee Usd */
            service_fee_usd: number;
            /**
             * Classiq Platform Fee Usd
             * @description Present only when the Classiq fee is itemised.
             */
            classiq_platform_fee_usd?: number | null;
            /** Actual Qpu Cost Usd */
            actual_qpu_cost_usd?: number | null;
            /** Total Usd */
            total_usd: number;
        };
        /**
         * BudgetPlan
         * @enum {string}
         */
        BudgetPlan: "payg" | "flex" | "premium";
        /**
         * CircuitFormat
         * @enum {string}
         */
        CircuitFormat: "qiskit_python" | "openqasm2" | "openqasm3" | "json" | "qmod";
        /** CircuitMetrics */
        CircuitMetrics: {
            /** Depth */
            depth: number;
            /** Gate Count */
            gate_count: number;
            /** Two Qubit Gate Count */
            two_qubit_gate_count: number;
            /** Width */
            width: number;
            /**
             * Estimated Duration Sec
             * @description Critical-path duration of one shot on the target.
             */
            estimated_duration_sec?: number | null;
            /** Constraint Violations */
            constraint_violations?: string[];
        };
        /** Constraints */
        Constraints: {
            /** Max Depth */
            max_depth?: number | null;
            /** Max Width */
            max_width?: number | null;
            /** Max Gate Count */
            max_gate_count?: number | null;
            /**
             * Error Bound
             * @description Classiq only: approximation error bound.
             */
            error_bound?: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Detail */
            detail?: string | null;
            /** Code */
            code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterpretContext */
        InterpretContext: {
            /**
             * Algorithm
             * @example QAOA
             * @example VQE
             */
            algorithm?: string | null;
            /** Problem Description */
            problem_description?: string | null;
            /** Target Metric */
            target_metric?: string | null;
        };
        /**
         * InterpretRequest
         * @example {
         *       "context": {
         *         "algorithm": "QAOA",
         *         "problem_description": "portfolio optimization with 10 assets",
         *         "target_metric": "maximize probability of low-energy states"
         *       },
         *       "result_format": "counts_dict",
         *       "result_payload": {
         *         "10": 24,
         *         "11": 496,
         *         "00": 480,
         *         "01": 24
         *       },
         *       "target_bitstrings": [
         *         "00",
         *         "11"
         *       ]
         *     }
         */
        InterpretRequest: {
            result_format: components["schemas"]["ResultFormat"];
            /** Result Payload */
            result_payload: {
                [key: string]: unknown;
            } | string;
            context?: components["schemas"]["InterpretContext"] | null;
            /** Target Bitstrings */
            target_bitstrings?: string[] | null;
            /**
             * Target Backend
             * @description If given, backend error rates are included in the analysis.
             */
            target_backend?: string | null;
            /**
             * Physical Qubits
             * @description Physical qubits the job ran on (enables readout-error analysis).
             */
            physical_qubits?: number[] | null;
            /** @default payg */
            budget_mode: components["schemas"]["BudgetPlan"];
        };
        /** InterpretResponse */
        InterpretResponse: {
            /** Job Id */
            job_id: string;
            /** Summary */
            summary: string;
            /** Key Metrics */
            key_metrics: {
                [key: string]: unknown;
            };
            /** Noise Analysis */
            noise_analysis: {
                [key: string]: unknown;
            }[];
            /** Business Interpretation */
            business_interpretation: string;
            /** Recommendations */
            recommendations: string[];
            /** Next Steps */
            next_steps: string[];
            /** Confidence */
            confidence: string;
            interpretation: components["schemas"]["Interpretation"];
            billing: components["schemas"]["Billing"];
            /** Created At */
            created_at: string;
        };
        /** Interpretation */
        Interpretation: {
            /** Summary */
            summary: string;
            /** Success Probability */
            success_probability?: number | null;
            /** Key Metrics */
            key_metrics?: {
                [key: string]: unknown;
            };
            /** Noise Concerns */
            noise_concerns?: string[];
            /** Noise Analysis */
            noise_analysis?: components["schemas"]["NoiseConcern"][];
            /** Business Interpretation */
            business_interpretation: string;
            /** Recommendations */
            recommendations?: string[];
            /** Next Steps */
            next_steps?: string[];
            /**
             * Confidence
             * @description low | medium | high
             */
            confidence: string;
        };
        /** JobDetail */
        JobDetail: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Target Backend */
            target_backend: string | null;
            /** Selected Backend */
            selected_backend: string | null;
            /** Total Usd */
            total_usd: number | null;
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
            /** Request */
            request: {
                [key: string]: unknown;
            } | null;
            /** Response */
            response: {
                [key: string]: unknown;
            } | null;
            /** Backend Results */
            backend_results: {
                [key: string]: unknown;
            }[];
        };
        /** JobList */
        JobList: {
            /** Items */
            items: components["schemas"]["JobSummary"][];
            /** Total */
            total: number;
        };
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Target Backend */
            target_backend: string | null;
            /** Selected Backend */
            selected_backend: string | null;
            /** Total Usd */
            total_usd: number | null;
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string | null;
        };
        /** NoiseConcern */
        NoiseConcern: {
            /** Kind */
            kind: string;
            /** Location */
            location: string;
            /** Value */
            value: number;
            /** Message */
            message: string;
        };
        /**
         * OptimizationBackend
         * @enum {string}
         */
        OptimizationBackend: "ibm_composer" | "classiq" | "auto";
        /**
         * OptimizeRequest
         * @example {
         *       "budget_mode": "payg",
         *       "circuit_format": "openqasm2",
         *       "circuit_payload": "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[2];\ncreg c[2];\nh q[0];\ncx q[0],q[1];\nmeasure q -> c;\n",
         *       "include_simulation": true,
         *       "optimization_backend": "auto",
         *       "optimization_level": 2,
         *       "redundancy_mode": {
         *         "mode": "fallback",
         *         "primary": "ibm_composer"
         *       },
         *       "shots": 1024,
         *       "target_backend": "ibm_sherbrooke"
         *     }
         */
        OptimizeRequest: {
            circuit_format: components["schemas"]["CircuitFormat"];
            /**
             * Circuit Payload
             * @description Source text (QASM2/QASM3/Qmod) or a JSON gate-list object.
             */
            circuit_payload: string | {
                [key: string]: unknown;
            };
            /**
             * Target Backend
             * @default ibm_sherbrooke
             * @example ibm_sherbrooke
             */
            target_backend: string;
            /**
             * Optimization Level
             * @default 2
             */
            optimization_level: number;
            /**
             * Shots
             * @default 1024
             */
            shots: number;
            /** @default payg */
            budget_mode: components["schemas"]["BudgetPlan"];
            /** @default auto */
            optimization_backend: components["schemas"]["OptimizationBackend"];
            constraints?: components["schemas"]["Constraints"];
            redundancy_mode?: components["schemas"]["RedundancyMode"];
            /**
             * Include Simulation
             * @default true
             */
            include_simulation: boolean;
            /**
             * Noisy Simulation
             * @description Simulate with the target backend's noise model (slower).
             * @default false
             */
            noisy_simulation: boolean;
            /**
             * Execute On Qpu
             * @description Submit the selected circuit to real IBM hardware. Requires server opt-in.
             * @default false
             */
            execute_on_qpu: boolean;
            /**
             * Target Bitstrings
             * @description Bitstrings considered 'success' for the interpretation.
             */
            target_bitstrings?: string[] | null;
            context?: components["schemas"]["InterpretContext"] | null;
        };
        /** OptimizeResponse */
        OptimizeResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Target Backend */
            target_backend: string;
            /** Backends Used */
            backends_used: components["schemas"]["OptimizationBackend"][];
            /** Results */
            results: {
                [key: string]: components["schemas"]["BackendResult"];
            };
            selected_result: components["schemas"]["SelectedResult"];
            transpiled_circuit: components["schemas"]["TranspiledCircuit"] | null;
            /** Gate Count Before */
            gate_count_before: number;
            /** Gate Count After */
            gate_count_after: number | null;
            /** Depth Before */
            depth_before: number;
            /** Depth After */
            depth_after: number | null;
            /** Estimated Qpu Runtime Sec */
            estimated_qpu_runtime_sec: number | null;
            /** Estimated Qpu Cost Usd */
            estimated_qpu_cost_usd: number | null;
            simulation_result: components["schemas"]["SimulationResult"] | null;
            interpretation: components["schemas"]["Interpretation"] | null;
            qpu_execution?: components["schemas"]["QpuExecution"] | null;
            billing: components["schemas"]["Billing"];
            /** Created At */
            created_at: string;
        };
        /** QpuExecution */
        QpuExecution: {
            /** Submitted */
            submitted: boolean;
            /** Ibm Job Id */
            ibm_job_id?: string | null;
            /** Status */
            status?: string | null;
            /** Usage Estimation Sec */
            usage_estimation_sec?: number | null;
            /** Actual Usage Sec */
            actual_usage_sec?: number | null;
            /** Counts */
            counts?: {
                [key: string]: number;
            } | null;
            /** Message */
            message?: string | null;
        };
        /** QuoteRequest */
        QuoteRequest: {
            circuit_format: components["schemas"]["CircuitFormat"];
            /**
             * Circuit Payload
             * @description Source text (QASM2/QASM3/Qmod) or a JSON gate-list object.
             */
            circuit_payload: string | {
                [key: string]: unknown;
            };
            /**
             * Target Backend
             * @default ibm_sherbrooke
             * @example ibm_sherbrooke
             */
            target_backend: string;
            /**
             * Optimization Level
             * @default 2
             */
            optimization_level: number;
            /**
             * Shots
             * @default 1024
             */
            shots: number;
            /** @default payg */
            budget_mode: components["schemas"]["BudgetPlan"];
            /** @default auto */
            optimization_backend: components["schemas"]["OptimizationBackend"];
            constraints?: components["schemas"]["Constraints"];
            redundancy_mode?: components["schemas"]["RedundancyMode"];
        };
        /** QuoteResponse */
        QuoteResponse: {
            /** Quote Id */
            quote_id: string;
            /** Target Backend */
            target_backend: string;
            /** Shots */
            shots: number;
            plan: components["schemas"]["BudgetPlan"];
            /** Estimates */
            estimates: {
                [key: string]: components["schemas"]["BackendEstimate"];
            };
            recommended_backend: components["schemas"]["OptimizationBackend"];
            /** Recommendation Reason */
            recommendation_reason: string;
            /** Estimated Qpu Runtime Sec */
            estimated_qpu_runtime_sec: number;
            /** Estimated Qpu Cost Usd */
            estimated_qpu_cost_usd: number;
            /** Service Fee Usd */
            service_fee_usd: number;
            /** Total Usd */
            total_usd: number;
            billing: components["schemas"]["Billing"];
            /** Valid Until */
            valid_until: string;
            /** Created At */
            created_at: string;
        };
        /** RedundancyMode */
        RedundancyMode: {
            /** @default fallback */
            mode: components["schemas"]["RedundancyModeName"];
            /** @default ibm_composer */
            primary: components["schemas"]["OptimizationBackend"];
            /**
             * Timeout Sec
             * @description Override the server fallback timeout.
             */
            timeout_sec?: number | null;
            /** @default qpu_cost */
            selection_metric: components["schemas"]["SelectionMetric"];
        };
        /**
         * RedundancyModeName
         * @enum {string}
         */
        RedundancyModeName: "single" | "parallel" | "fallback";
        /**
         * ResultFormat
         * @enum {string}
         */
        ResultFormat: "ibm_job_result_json" | "counts_dict" | "csv";
        /** SelectedResult */
        SelectedResult: {
            backend: components["schemas"]["OptimizationBackend"];
            /** Reason */
            reason: string;
            /** Depth */
            depth?: number | null;
            /** Gate Count */
            gate_count?: number | null;
        };
        /**
         * SelectionMetric
         * @enum {string}
         */
        SelectionMetric: "qpu_cost" | "depth" | "gate_count";
        /** SimulationResult */
        SimulationResult: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Shots */
            shots: number;
            /**
             * Noisy
             * @default false
             */
            noisy: boolean;
        };
        /** TranspiledCircuit */
        TranspiledCircuit: {
            /**
             * Format
             * @description openqasm3 | openqasm2 | qmod
             */
            format: string;
            /** Source */
            source: string;
            /**
             * Layout
             * @description virtual qubit index (str) -> physical qubit.
             */
            layout?: {
                [key: string]: number;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    optimize_v2_optimize_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-Payload-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    quote_v2_quote_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-Payload-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    interpret_v2_interpret_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-Payload-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_jobs_v2_jobs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v2_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-Payload-Key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
