version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      qiskit:
        patterns: ["qiskit*"]
      dev:
        dependency-type: development
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      next:
        patterns: ["next", "react", "react-dom", "@types/react*"]
      dev:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
